name: Test Secrets

on:
  pull_request_target:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for approval
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.ref }}
        check-name: Get Approval
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Secret
      run: |
        echo "showing my secrets"
        echo "${MY_SECRET:-not here}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
