name: Test Secrets

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for the labeler
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: Team Label
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
    - name: Verify PR labels
      id: verify
      continue-on-error: true
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'safe to test'
        pull-request-number: '${{ github.event.pull_request.number }}'
        disable-reviews: true  # To not autoapprove changes
    #- name: Validate PR
    #  if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    #  run: echo "This PR is safe!"
    #- name: Raise on invalid PR
    #  if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe to test') }}
    #  run: |
    #    echo "This PR is not safe to test. Exiting."
    #    exit 1
    - name: Add verification comment
      if: steps.verify.outcome != 'success'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **Hi there 👋 Thanks for your contribution!**

          The team will review the PR shortly! Once it has been labeled as `safe to test`, the CI workflows
          will start executing and we'll be able to make sure everything is working as expected.

          Let us know if you need any help!
    - name: Kill workflow
      if: steps.verify.outcome != 'success'
      run: |
        exit 1

    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Secret
      run: |
        echo "showing my secrets"
        echo "${MY_SECRET:-not here}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
