name: Test Secrets

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for the labeler
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: Team Label
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
    - name: Validate PR
      if: contains(github.event.pull_request.labels.*.name, 'safe to test')
      run: echo "This PR is safe!"
    - name: Raise on invalid PR
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe to test') }}
      run: |
        echo "This PR is not safe to test. Exiting."
        exit 1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Secret
      run: |
        echo "showing my secrets"
        echo "${MY_SECRET:-not here}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
