name: Test Secrets

on:
  pull_request:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Secret
      run: |
        echo "showing my secrets"
        echo "${MY_SECRET:-not here}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
