name: Test Secrets

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
    - name: Wait for approval
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: Approval
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Secret
      run: |
        echo "showing my secrets"
        echo "${MY_SECRET:-not here}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
